# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: dev
      MYSQL_PASSWORD : holabebe
      ports:
      # <Port exposed> : < MySQL Port running inside container>
        3308:3308
      expose:
      # Opens port 3306 on the container
        3308
      # Where our data will be persisted

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8090