/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 16-feb.-2020 6:10:34 p. m. 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `balance` CASCADE
;

DROP TABLE IF EXISTS `bitacora` CASCADE
;

DROP TABLE IF EXISTS `descuento` CASCADE
;

DROP TABLE IF EXISTS `parqueadero` CASCADE
;

DROP TABLE IF EXISTS `precio` CASCADE
;

DROP TABLE IF EXISTS `recibo_tarifa` CASCADE
;

DROP TABLE IF EXISTS `suscripcion` CASCADE
;

DROP TABLE IF EXISTS `usuario` CASCADE
;

DROP TABLE IF EXISTS `usuario_suscripcion` CASCADE
;

DROP TABLE IF EXISTS `vehiculo` CASCADE
;

/* Create Tables */

CREATE TABLE `balance`
(
	`id_balance` INT NOT NULL AUTO_INCREMENT,
	`fecha` DATE NULL,
	`recaudo` DOUBLE(10,2) NULL,
	`unidad_tiempo` VARCHAR(50) NULL,
	CONSTRAINT `PK_balance` PRIMARY KEY (`id_balance` ASC)
)

;

CREATE TABLE `bitacora`
(
	`id_bitacora` INT NOT NULL AUTO_INCREMENT,
	`fecha` DATE NULL,
	`id_usuario` INT NULL,
	`id_parqueadero` INT NULL,
	`id_vehiculo` INT NULL,
	`hora_entrada` DATETIME NULL,
	`hora_salida` DATETIME NULL,
	`unidad_tiempo` VARCHAR(50) NULL,
	`valor` DOUBLE(10,2) NULL,
	CONSTRAINT `PK_bitacora` PRIMARY KEY (`id_bitacora` ASC)
)

;

CREATE TABLE `descuento`
(
	`id_descuento` INT NOT NULL AUTO_INCREMENT,
	`nombre` VARCHAR(50) NULL,
	`fecha` DATE NULL,
	`valor` DOUBLE(10,2) NULL,
	CONSTRAINT `PK_descuento` PRIMARY KEY (`id_descuento` ASC)
)

;

CREATE TABLE `parqueadero`
(
	`id_parqueadero` INT NOT NULL AUTO_INCREMENT,
	`nombre` VARCHAR(50) NULL,
	`direccion` VARCHAR(50) NULL,
	`cupo_maximo` INT NULL,
	`cupo_disponible` INT NULL,
	CONSTRAINT `PK_parqueadero` PRIMARY KEY (`id_parqueadero` ASC)
)

;

CREATE TABLE `precio`
(
	`id_precio` INT NOT NULL AUTO_INCREMENT,
	`unidad_tiempo` VARCHAR(50) NULL,
	`valor` DOUBLE(10,2) NULL,
	`vehiculo` VARCHAR(50) NULL,
	CONSTRAINT `PK_precio` PRIMARY KEY (`id_precio` ASC)
)

;

CREATE TABLE `recibo_tarifa`
(
	`id_factura` INT NOT NULL AUTO_INCREMENT,
	`fecha_inicio` DATETIME NULL,
	`fecha_fin` DATETIME NULL,
	`subtotal` DOUBLE(10,2) NULL,
	`descuento` DOUBLE(10,2) NULL,
	`total` DOUBLE(10,2) NULL,
	`suscripcion` INT NULL,
	CONSTRAINT `PK_recibo_tarifa` PRIMARY KEY (`id_factura` ASC)
)

;

CREATE TABLE `suscripcion`
(
	`id_suscripcion` INT NOT NULL AUTO_INCREMENT,
	`tipo` VARCHAR(50) NULL,
	`vehiculo` INT NULL,
	`fecha_inicio` DATE NULL,
	`fecha_fin` DATE NULL,
	`precio` DOUBLE(10,2) NULL,
	`activo` BOOL NULL,
	CONSTRAINT `PK_suscripcion` PRIMARY KEY (`id_suscripcion` ASC)
)

;

CREATE TABLE `usuario`
(
	`id_usuario` INT NOT NULL AUTO_INCREMENT,
	`nombre` VARCHAR(50) NULL,
	`documento` VARCHAR(50) NULL,
	`tipo` VARCHAR(50) NULL,
	CONSTRAINT `PK_usuario` PRIMARY KEY (`id_usuario` ASC)
)

;

CREATE TABLE `usuario_suscripcion`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`suscripcion` INT NULL,
	`usuario` INT NULL,
	CONSTRAINT `PK_usuario_suscripcion` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `vehiculo`
(
	`id_vehiculo` INT NOT NULL AUTO_INCREMENT,
	`tipo` VARCHAR(50) NULL,
	`placa` VARCHAR(50) NULL,
	`color` VARCHAR(50) NULL,
	CONSTRAINT `PK_vehiculo` PRIMARY KEY (`id_vehiculo` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `bitacora` 
 ADD INDEX `IXFK_bitacora_parqueadero` (`id_parqueadero` ASC)
;

ALTER TABLE `bitacora` 
 ADD INDEX `IXFK_bitacora_usuario` (`id_usuario` ASC)
;

ALTER TABLE `bitacora` 
 ADD INDEX `IXFK_bitacora_vehiculo` (`id_vehiculo` ASC)
;

ALTER TABLE `recibo_tarifa` 
 ADD INDEX `IXFK_recibo_tarifa_usuario_suscripcion` (`suscripcion` ASC)
;

ALTER TABLE `suscripcion` 
 ADD INDEX `IXFK_suscripcion_vehiculo` (`vehiculo` ASC)
;

ALTER TABLE `usuario_suscripcion` 
 ADD INDEX `IXFK_usuario_suscripcion_suscripcion` (`suscripcion` ASC)
;

ALTER TABLE `usuario_suscripcion` 
 ADD INDEX `IXFK_usuario_suscripcion_usuario` (`usuario` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `bitacora` 
 ADD CONSTRAINT `FK_bitacora_parqueadero`
	FOREIGN KEY (`id_parqueadero`) REFERENCES `parqueadero` (`id_parqueadero`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `bitacora` 
 ADD CONSTRAINT `FK_bitacora_usuario`
	FOREIGN KEY (`id_usuario`) REFERENCES `usuario` (`id_usuario`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `bitacora` 
 ADD CONSTRAINT `FK_bitacora_vehiculo`
	FOREIGN KEY (`id_vehiculo`) REFERENCES `vehiculo` (`id_vehiculo`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `recibo_tarifa` 
 ADD CONSTRAINT `FK_recibo_tarifa_usuario_suscripcion`
	FOREIGN KEY (`suscripcion`) REFERENCES `usuario_suscripcion` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `suscripcion` 
 ADD CONSTRAINT `FK_suscripcion_vehiculo`
	FOREIGN KEY (`vehiculo`) REFERENCES `vehiculo` (`id_vehiculo`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `usuario_suscripcion` 
 ADD CONSTRAINT `FK_usuario_suscripcion_suscripcion`
	FOREIGN KEY (`suscripcion`) REFERENCES `suscripcion` (`id_suscripcion`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `usuario_suscripcion` 
 ADD CONSTRAINT `FK_usuario_suscripcion_usuario`
	FOREIGN KEY (`usuario`) REFERENCES `usuario` (`id_usuario`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1 
;
