spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/easy_parking?autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver 
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5Dialect
  security:
    user:
      name: kevin
      password: kevin2